Testing_Old/SpecFlow-Examples-master/ASP.NET-MVC/BookShop/BookShop.Mvc/Models/Book.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace BookShop.Mvc.Models
{
    public class Book
    {
        [Key]
        public int Id { get; set; }

        [Required]
        public string Author { get; set; }

        [Required]
        public string Title { get; set; }

        [Required]
        [Range(0d, double.MaxValue)]
        public decimal Price { get; set; }

        public List<OrderLine> OrderLines { get; set; }
    }
}

Testing_Old/SpecFlow-Examples-master/ASP.NET-MVC/BookShop/BookShop.Mvc/Models/DatabaseContext.cs
using System.Data.Entity;

namespace BookShop.Mvc.Models
{
    public class DatabaseContext
        : DbContext
    {
        public DatabaseContext()
            : base(@"Data Source=(localdb)\v11.0;Initial Catalog=BookShop;Integrated Security=True;MultipleActiveResultSets=True")
        {
        }
        
        public DbSet<Order> Orders { get; set; }

        public DbSet<Book> Books { get; set; }

        public DbSet<OrderLine> OrderLines { get; set; }
    }
}

Testing_Old/SpecFlow-Examples-master/ASP.NET-MVC/BookShop/BookShop.Mvc/Models/Order.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;

namespace BookShop.Mvc.Models
{
    public class Order
    {
        [Key]
        public int Id { get; set; }

        [Required]
        public string Status { get; set; }

        [Required]
        public decimal Price => OrderLines.Sum(ol => ol.Price);

        public List<OrderLine> OrderLines { get; set; }
    }
}

Testing_Old/SpecFlow-Examples-master/ASP.NET-MVC/BookShop/BookShop.Mvc/Models/OrderLine.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace BookShop.Mvc.Models
{
    public class OrderLine
    {
        public virtual Book Book { get; set; }

        [Key]
        [Required]
        [ForeignKey(nameof(Models.Book))]
        [Column(Order = 0)]
        public int BookId { get; set; }

        public virtual Order Order { get; set; }

        [Key]
        [Required]
        [ForeignKey(nameof(Models.Order))]
        [Column(Order = 1)]
        public int OrderId { get; set; }

        [Range(1, int.MaxValue)]
        [Required]
        public int Quantity { get; set; }

        public decimal Price => Quantity * Book.Price;
    }
}

Testing_Old/SpecFlow-Examples-master/ASP.NET-MVC/BookShop/BookShop.Mvc/Models/ShoppingCart.cs
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;

namespace BookShop.Mvc.Models
{
    public class ShoppingCart
    {
        private readonly List<OrderLine> _orderLines = new List<OrderLine>();

        [DisplayName("Total Price")]
        public decimal Price => _orderLines.Sum(li => li.Price);

        public int Count => _orderLines.Sum(li => li.Quantity);

        public IEnumerable<OrderLine> Lines => _orderLines;

        public void AddLineItem(OrderLine lineItem)
        {
            _orderLines.Add(lineItem);
        }

        public void RemoveLineItem(int bookId)
        {
            _orderLines.Remove(_orderLines.FirstOrDefault(li => li.Book.Id == bookId));
        }
    }
}

Testing_Old/SpecFlow-Examples-master/ASP.NET-MVC/BookShop/BookShop.Mvc/Controllers/CatalogController.cs
using System.Linq;
using System.Web.Mvc;
using BookShop.Mvc.Models;
using LinqKit;

namespace BookShop.Mvc.Controllers
{
    public class CatalogController : Controller
    {
        public ActionResult Search(string searchTerm)
        {
            using (var db = new DatabaseContext())
            {
                var terms = searchTerm?.Split(' ') ?? new string[0];
                var predicate = terms.Aggregate(
                    PredicateBuilder.New<Book>(string.IsNullOrEmpty(searchTerm)),
                    (acc, term) => acc.Or(b => b.Title.Contains(term))
                                      .Or(b => b.Author.Contains(term)));

                var books = db.Books.AsExpandable()
                                    .Where(predicate)
                                    .OrderBy(b => b.Title)
                                    .ToArray();

                return View("List", books);
            }
        }

        public ActionResult Details(int id)
        {
            using (var db = new DatabaseContext())
            {
                var book = db.Books.First(b => b.Id == id);
                return View(book);
            }
        }
    }
}

Testing_Old/SpecFlow-Examples-master/ASP.NET-MVC/BookShop/BookShop.Mvc/Controllers/HomeController.cs
using System.Linq;
using System.Web.Mvc;
using BookShop.Mvc.Models;

namespace BookShop.Mvc.Controllers
{
    public class HomeController
        : Controller
    {
        public ActionResult Index()
        {
            using (var db = new DatabaseContext())
            {
                var cheapBooks = db.Books.OrderBy(b => b.Price)
                                         .Take(3)
                                         .OrderBy(b => b.Title)
                                         .ToArray();
                return View(cheapBooks);
            }
        }
    }
}

Testing_Old/SpecFlow-Examples-master/ASP.NET-MVC/BookShop/BookShop.Mvc/Controllers/ShoppingCartController.cs
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web.Mvc;
using BookShop.Mvc.Models;

namespace BookShop.Mvc.Controllers
{
    public class ShoppingCartController
        : Controller
    {
        public const string CartSessionKey = "CART";

        public ActionResult Index()
        {
            var shoppingCart = GetShoppingCart();
            return View(shoppingCart);
        }

        public ActionResult Add(int bookId)
        {
            using (var db = new DatabaseContext())
            {
                var shoppingCart = GetShoppingCart();

                var existingLine = shoppingCart.Lines.SingleOrDefault(l => l.Book.Id == bookId);
                if (existingLine != null)
                {
                    existingLine.Quantity++;
                }
                else
                {
                    var book = db.Books.First(b => b.Id == bookId);

                    var newOrderLine = new OrderLine
                    {
                        Book = book,
                        Quantity = 1
                    };

                    shoppingCart.AddLineItem(newOrderLine);
                }

                ViewData.Model = shoppingCart;
                return RedirectToAction(nameof(Index));
            }
        }

        [HttpGet]
        public ActionResult DeleteItem(int id)
        {
            var shoppingCart = GetShoppingCart();
            shoppingCart.RemoveLineItem(id);

            ViewData.Model = shoppingCart;
            return RedirectToAction("Index");
        }

        [HttpPost]
        [ValidateInput(true)]
        public ActionResult Edit(EditArguments editArgs)
        {
            if (!ModelState.IsValid)
            {
                return Index();
            }

            var shoppingCart = GetShoppingCart();
            int bookId = editArgs.BookId;
            int quantity = editArgs.Quantity;

            if (quantity > 0)
            {
                var existingLine = shoppingCart.Lines.Single(l => l.Book.Id == bookId);
                existingLine.Quantity = quantity;
            }
            else
            {
                shoppingCart.RemoveLineItem(bookId);
            }

            return RedirectToAction("Index");
        }

        private ShoppingCart GetShoppingCart()
        {
            if (HttpContext.Session[CartSessionKey] is ShoppingCart sc)
            {
                return sc;
            }

            var cart = new ShoppingCart();
            HttpContext.Session[CartSessionKey] = cart;
            return cart;
        }

        public class EditArguments
        {
            public int BookId { get; set; }

            [Range(0, 10)]
            public int Quantity { get; set; }
        }
    }
}

Testing_Old/SpecFlow-Examples-master/ASP.NET-MVC/BookShop/BookShop.Mvc/Views/Catalog/Details.cshtml
@using BookShop.Mvc.Models

@model Book

@{
    ViewBag.Title = $"{Model.Title}";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1 class="page-header">@Model.Title <small>by @Model.Author</small></h1>

<dl class="dl-horizontal">
    <dt>Title</dt>
    <dd>@Model.Title</dd>

    <dt>Author(s)</dt>
    <dd>@Model.Author</dd>

    <dt>Price</dt>
    <dd>&euro; @Model.Price.ToString("0.00")</dd>

    <dt>Id</dt>
    <dd>@Model.Id</dd>
</dl>

@Html.ActionLink("Add to cart", "Add", "ShoppingCart", new { bookId = Model.Id }, new { @class = "btn btn-primary" })

Testing_Old/SpecFlow-Examples-master/ASP.NET-MVC/BookShop/BookShop.Mvc/Views/Catalog/List.cshtml
@using BookShop.Mvc.Models
@model IEnumerable<Book>

@{
    ViewBag.Title = "Books";
}

<div class="jumbotron">
    <h1>Books</h1>
</div>

<div class="table-responsive">
    <table class="table table-striped" id="searchResultTable">
        <thead>
            <tr>
                <th><em>Title</em></th>
                <th><em>Author</em></th>
                <th><em>Price</em></th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var book in Model)
            {
                <tr>
                    <td><h4>@Html.ActionLink(book.Title, "Details", "Catalog", new { id = book.Id }, new { })</h4></td>
                    <td>@book.Author</td>
                    <td>&euro; @book.Price.ToString("0.00")</td>
                    <td>@Html.ActionLink("Add to cart", "Add", "ShoppingCart", new { bookId = book.Id }, new { @class = "btn btn-primary" })</td>
                </tr>
            }
        </tbody>
    </table>
</div>

Testing_Old/SpecFlow-Examples-master/ASP.NET-MVC/BookShop/BookShop.Mvc/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

Testing_Old/SpecFlow-Examples-master/ASP.NET-MVC/BookShop/BookShop.Mvc/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

Testing_Old/SpecFlow-Examples-master/ASP.NET-MVC/BookShop/BookShop.Mvc/Views/Home/Index.cshtml
@using BookShop.Mvc.Models

@model IEnumerable<Book>

@{
    ViewBag.Title = "Home";
}

<div class="jumbotron">
    <h1 class="page-header">Bookshop</h1>
    <p class="lead">The bookshop example demonstrates using SpecFlow with Selenium-based UI tests.</p>
    <p><a href="http://specflow.org/" class="btn btn-primary btn-lg" target="_blank">Learn more &raquo;</a></p>
</div>

<h2>Best offers</h2>

<div class="table-responsive">
    <table class="table table-striped">
        <caption>
            @Html.ActionLink("View all offers", "Search", "Catalog", new { }, new { @class = "btn btn-default" })
        </caption>
        <thead>
            <tr>
                <th><em>Title</em></th>
                <th><em>Author</em></th>
                <th><em>Price</em></th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var book in Model)
            {
                <tr>
                    <td><h4>@Html.ActionLink(book.Title, "Details", "Catalog", new { id = book.Id }, new { })</h4></td>
                    <td>@book.Author</td>
                    <td>&euro; @book.Price.ToString("0.00")</td>
                    <td>@Html.ActionLink("Add to cart", "Add", "ShoppingCart", new { bookId = book.Id }, new { @class = "btn btn-primary" })</td>
                </tr>
            }
        </tbody>
    </table>
</div>

Testing_Old/SpecFlow-Examples-master/ASP.NET-MVC/BookShop/BookShop.Mvc/Views/ShoppingCart/Index.cshtml
@using BookShop.Mvc.Models;

@model ShoppingCart

@{
    ViewBag.Title = "Shopping Cart";
}

<h2>Shopping Cart</h2>

<div class="table-responsive">
    <table class="table table-striped">
        <thead>
        <tr>
            <th><em>Title</em></th>
            <th><em>Author</em></th>
            <th><em>Quantity</em></th>
            <th><em>Price</em></th>
        </tr>
        </thead>
        <tbody>
        @foreach (var orderLine in Model.Lines)
        {
            <tr>
                <td><h4>@Html.ActionLink(orderLine.Book.Title, "Details", "Catalog", new { id = orderLine.Book.Id }, new { })</h4></td>
                <td>@orderLine.Book.Author</td>
                <td>@orderLine.Quantity</td>
                <td>&euro; @orderLine.Price.ToString("0.00")</td>
            </tr>
        }
        </tbody>
        <tfoot>
        <tr>
            <th><h4><strong>Total</strong></h4></th>
            <th></th>
            <th>@Model.Count</th>
            <th>&euro; @Model.Price.ToString("0.00")</th>
        </tr>
        </tfoot>
    </table>
</div>